import os
from datetime import timedelta
from feast import Field, FeatureView
from feast.stream_feature_view import StreamFeatureView
from feast.types import Float32, Int64, String
from feast import KafkaSource, FileSource
from feast.data_format import JsonFormat

from entities import customer
from schema_loaders import infer_application_fields, infer_external_fields, infer_dwh_fields_from_json
from feast import stream_feature_view

# Environment-driven configuration (single source of truth via env)
BOOTSTRAP = os.getenv("FEAST_KAFKA_BROKERS", "host.minikube.internal:39092")
TOPIC_APP_FEATURES = os.getenv("FEAST_TOPIC_APP_FEATURES", "hc.application_features")
TOPIC_EXTERNAL = os.getenv("FEAST_TOPIC_EXTERNAL", "hc.application_ext")
TOPIC_DWH = os.getenv("FEAST_TOPIC_DWH", "hc.application_dwh")
TS_APP = os.getenv("FEAST_TS_FIELD_APP", "ts")
TS_EXT = os.getenv("FEAST_TS_FIELD_EXT", "ts")
TS_DWH = os.getenv("FEAST_TS_FIELD_DWH", "ts")


def _build_json_schema(fields: list[Field], ts_field: str) -> str:
    type_map = {
        Int64: {"type": "integer"},
        Float32: {"type": "number"},
        String: {"type": "string"},
    }
    props: dict[str, dict] = {
        "sk_id_curr": {"type": "string"},
        ts_field: {"type": "number"},
    }
    for f in fields:
        # f.dtype is a Type, compare via is
        if f.dtype in type_map:
            props[f.name] = type_map[f.dtype]
        else:
            props[f.name] = {"type": "string"}
    schema = {
        "type": "object",
        "properties": props,
        "additionalProperties": True,
    }
    import json as _json
    return _json.dumps(schema)


def _kafka_source_with_optional_batch(
    name: str,
    topic: str,
    ts_field: str,
    brokers: str,
    fields: list[Field],
    batch_source: FileSource,
) -> KafkaSource:
    """Construct a KafkaSource and attach batch_source if supported (Feast >= 0.47).

    Falls back to creating a KafkaSource without batch_source if the constructor
    does not accept it (older Feast versions).
    """
    schema_json = _build_json_schema(fields, ts_field)
    fmt = JsonFormat(schema_json)
    base_kwargs = dict(name=name, topic=topic, timestamp_field=ts_field, message_format=fmt)

    # Try with batch_source
    for broker_kw in ("kafka_bootstrap_servers", "kafka_brokers", "bootstrap_servers", "brokers"):
        try:
            kwargs = {broker_kw: BOOTSTRAP, **base_kwargs, "batch_source": batch_source}
            return KafkaSource(**kwargs)  # type: ignore[arg-type]
        except TypeError:
            continue

    # Fallback: without batch_source
    for broker_kw in ("kafka_bootstrap_servers", "kafka_brokers", "bootstrap_servers", "brokers"):
        try:
            kwargs = {broker_kw: BOOTSTRAP, **base_kwargs}
            return KafkaSource(**kwargs)  # type: ignore[arg-type]
        except TypeError:
            continue
    return KafkaSource(brokers=BOOTSTRAP, **base_kwargs)  # type: ignore[arg-type]


# Dynamically inferred from Kafka topic hc.application_features
# Schema auto-generated by generate_schemas_from_kafka.py
_app_fields = infer_application_fields()

# Batch sources (defined early so they can be referenced by stream sources when supported)
application_batch_source = FileSource(
    name="application_batch_source",
    path="/tmp/application_features.parquet",
    timestamp_field=TS_APP,
)

external_batch_source = FileSource(
    name="external_batch_source",
    path="/tmp/external_features.parquet",
    timestamp_field=TS_EXT,
)

dwh_batch_source = FileSource(
    name="dwh_batch_source",
    path="/tmp/dwh_features.parquet",
    timestamp_field=TS_DWH,
)

application_features_source = _kafka_source_with_optional_batch(
    name="application_features_source",
    topic=TOPIC_APP_FEATURES,
    ts_field=TS_APP,
    brokers=BOOTSTRAP,
    fields=_app_fields,
    batch_source=application_batch_source,
)

# Dynamically inferred from Kafka topic hc.application_ext
# Schema auto-generated by generate_schemas_from_kafka.py
_ext_fields = infer_external_fields()

external_features_source = _kafka_source_with_optional_batch(
    name="external_features_source",
    topic=TOPIC_EXTERNAL,
    ts_field=TS_EXT,
    brokers=BOOTSTRAP,
    fields=_ext_fields,
    batch_source=external_batch_source,
)

# Dynamically inferred from Kafka topic hc.application_dwh
# Schema auto-generated by generate_schemas_from_kafka.py
_dwh_fields = infer_dwh_fields_from_json()

dwh_features_source = _kafka_source_with_optional_batch(
    name="dwh_features_source",
    topic=TOPIC_DWH,
    ts_field=TS_DWH,
    brokers=BOOTSTRAP,
    fields=_dwh_fields,
    batch_source=dwh_batch_source,
)

# (Batch sources already defined above)

# For Feast 0.40.1, StreamFeatureView requires both stream_source and batch_source
# We need to modify the KafkaSource to include batch_source reference
# Create StreamFeatureViews with proper batch source configuration on the SFV itself
def _make_stream_fv(name: str, schema: list[Field], stream_src, batch_src, ttl_days: int) -> StreamFeatureView:
    """Create a StreamFeatureView using source only.

    On Feast 0.47+, batch_source must be attached to the DataSource (KafkaSource),
    not passed to StreamFeatureView. We rely on the KafkaSource being built with
    a batch_source when supported. Older versions also accept source-only.
    """
    kwargs_common = dict(name=name, entities=[customer], ttl=timedelta(days=ttl_days), schema=schema, online=True)
    try:
        return StreamFeatureView(source=stream_src, **kwargs_common)  # type: ignore[arg-type]
    except TypeError:
        return StreamFeatureView(stream_source=stream_src, **kwargs_common)  # type: ignore[arg-type]


fv_application_features = _make_stream_fv(
    name="application_features",
    schema=_app_fields,
    stream_src=application_features_source,
    batch_src=application_batch_source,
    ttl_days=1,
)

fv_external = _make_stream_fv(
    name="external_features",
    schema=_ext_fields,
    stream_src=external_features_source,
    batch_src=external_batch_source,
    ttl_days=7,
)

fv_dwh = _make_stream_fv(
    name="dwh_features",
    schema=_dwh_fields,
    stream_src=dwh_features_source,
    batch_src=dwh_batch_source,
    ttl_days=7,
)

# Note: StreamFeatureViews above support both:
# - Offline/Training: via batch_source (MinIO Parquet files)
# - Online/Serving: via online store (Redis)
# No need for separate batch FeatureViews - this prevents name conflicts
# and ensures training/serving use identical feature definitions
