"""
Schema loaders for dynamic Feast feature inference.

Loads feature schemas from JSON files generated by sampling Kafka topics.
This approach ensures Feast StreamFeatureViews stay in sync with actual
data pipeline outputs without manual schema maintenance.
"""

import json
from pathlib import Path
from typing import List
from feast import Field
from feast.types import Float32, Int64, String


def _load_schema_from_json(json_file: Path) -> List[Field]:
    """Load Feast fields from JSON schema file.

    JSON format: [{"name": "feature_name", "type": "Int64"}, ...]
    """
    if not json_file.exists():
        raise FileNotFoundError(f"Schema file not found: {json_file}")

    with open(json_file, 'r') as f:
        schema = json.load(f)

    # Map string type names to Feast types
    type_map = {
        "Int64": Int64,
        "Float32": Float32,
        "String": String,
    }

    fields = []
    for field_def in schema:
        field_name = field_def["name"]
        field_type_str = field_def["type"]
        field_type = type_map.get(field_type_str, String)  # Default to String
        fields.append(Field(name=field_name, dtype=field_type))

    return fields


def infer_application_fields() -> List[Field]:
    """Dynamically load application features schema from JSON.

    Schema generated by sampling Kafka topic hc.application_features.
    Run generate_schemas_from_kafka.py to regenerate.
    """
    schema_file = Path(__file__).parent / "feature_schema" / "application_schema.json"
    return _load_schema_from_json(schema_file)


def infer_external_fields() -> List[Field]:
    """Dynamically load external features schema from JSON.

    Schema generated by sampling Kafka topic hc.application_ext.
    Run generate_schemas_from_kafka.py to regenerate.
    """
    schema_file = Path(__file__).parent / "feature_schema" / "external_schema.json"
    return _load_schema_from_json(schema_file)


def infer_dwh_fields_from_json() -> List[Field]:
    """Dynamically load DWH features schema from JSON.

    Schema generated by sampling Kafka topic hc.application_dwh.
    Run generate_schemas_from_kafka.py to regenerate.
    """
    schema_file = Path(__file__).parent / "feature_schema" / "dwh_schema.json"
    return _load_schema_from_json(schema_file)
