{{
  config(
    materialized='table',
    description='Credit card features aggregated at SK_ID_CURR level'
  )
}}

WITH base AS (
    SELECT *
    FROM {{ source('application_dwh', 'credit_card_balance') }}
),
agg AS (
    SELECT
        SK_ID_CURR,

        /* === BASIC UTILIZATION FEATURES === */
        count() AS CC_MONTHS_COUNT,
        uniq(SK_ID_PREV) AS CC_CARDS_COUNT,

        avg(AMT_BALANCE / nullIf(AMT_CREDIT_LIMIT_ACTUAL, 0)) AS CC_UTILIZATION_MEAN,
        max(AMT_BALANCE / nullIf(AMT_CREDIT_LIMIT_ACTUAL, 0)) AS CC_UTILIZATION_MAX,
        stddevSamp(AMT_BALANCE / nullIf(AMT_CREDIT_LIMIT_ACTUAL, 0)) AS CC_UTILIZATION_STD,

        countIf(AMT_CREDIT_LIMIT_ACTUAL > 0 AND AMT_BALANCE / AMT_CREDIT_LIMIT_ACTUAL > 0.8) AS CC_HIGH_UTIL_MONTHS,
        countIf(AMT_CREDIT_LIMIT_ACTUAL > 0 AND AMT_BALANCE / AMT_CREDIT_LIMIT_ACTUAL > 1.0) AS CC_OVER_LIMIT_MONTHS,
        countIf(AMT_CREDIT_LIMIT_ACTUAL > 0 AND AMT_BALANCE / AMT_CREDIT_LIMIT_ACTUAL > 0.8) / cast(count(), 'Float64') AS CC_HIGH_UTIL_RATIO,

        /* === PAYMENT BEHAVIOR FEATURES === */
        avg(AMT_PAYMENT_CURRENT / nullIf(AMT_BALANCE, 0)) AS CC_PAYMENT_RATIO_MEAN,
        min(AMT_PAYMENT_CURRENT / nullIf(AMT_BALANCE, 0)) AS CC_PAYMENT_RATIO_MIN,

        avg(AMT_PAYMENT_CURRENT / nullIf(AMT_INST_MIN_REGULARITY, 0)) AS CC_MIN_PAYMENT_RATIO,
        countIf(AMT_INST_MIN_REGULARITY IS NOT NULL AND AMT_PAYMENT_CURRENT < AMT_INST_MIN_REGULARITY) AS CC_UNDERPAY_MONTHS,
        countIf(AMT_INST_MIN_REGULARITY IS NOT NULL AND AMT_PAYMENT_CURRENT < AMT_INST_MIN_REGULARITY) / cast(count(), 'Float64') AS CC_UNDERPAY_RATIO,

        countIf(AMT_PAYMENT_CURRENT = 0) AS CC_NO_PAYMENT_MONTHS,
        countIf(AMT_PAYMENT_CURRENT = 0) / cast(count(), 'Float64') AS CC_NO_PAYMENT_RATIO,

        /* === DPD (DELINQUENCY) FEATURES === */
        sumIf(SK_DPD, SK_DPD IS NOT NULL) AS CC_DPD_TOTAL,
        avg(SK_DPD) AS CC_DPD_MEAN,
        max(SK_DPD) AS CC_DPD_MAX,

        countIf(SK_DPD > 0) AS CC_DPD_MONTHS,
        countIf(SK_DPD BETWEEN 1 AND 30) AS CC_DPD_1_30_MONTHS,
        countIf(SK_DPD BETWEEN 31 AND 60) AS CC_DPD_31_60_MONTHS,
        countIf(SK_DPD > 60) AS CC_DPD_60PLUS_MONTHS,

        countIf(SK_DPD > 0) / cast(count(), 'Float64') AS CC_DPD_RATIO,
        countIf(SK_DPD > 60) / cast(count(), 'Float64') AS CC_SEVERE_DPD_RATIO,

        /* === SPENDING BEHAVIOR FEATURES === */
        sum(AMT_DRAWINGS_CURRENT) AS CC_TOTAL_DRAWINGS,
        avg(AMT_DRAWINGS_CURRENT) AS CC_DRAWINGS_MEAN,
        stddevSamp(AMT_DRAWINGS_CURRENT) AS CC_DRAWINGS_STD,

        sum(AMT_DRAWINGS_ATM_CURRENT) AS CC_ATM_TOTAL,
        sum(AMT_DRAWINGS_POS_CURRENT) AS CC_POS_TOTAL,
        sum(AMT_DRAWINGS_OTHER_CURRENT) AS CC_OTHER_TOTAL,

        sum(AMT_DRAWINGS_ATM_CURRENT) / nullIf(sum(AMT_DRAWINGS_CURRENT), 0) AS CC_ATM_RATIO,
        sum(AMT_DRAWINGS_POS_CURRENT) / nullIf(sum(AMT_DRAWINGS_CURRENT), 0) AS CC_POS_RATIO,

        avg(CNT_DRAWINGS_CURRENT) AS CC_TXN_FREQ_MEAN,
        sum(CNT_DRAWINGS_ATM_CURRENT) AS CC_ATM_TXN_COUNT,
        sum(CNT_DRAWINGS_POS_CURRENT) AS CC_POS_TXN_COUNT,

        /* === TEMPORAL PATTERNS === */
        min(MONTHS_BALANCE) AS CC_EARLIEST_MONTH,
        max(MONTHS_BALANCE) AS CC_LATEST_MONTH,

        countIf(AMT_DRAWINGS_CURRENT = 0) AS CC_INACTIVE_MONTHS,
        countIf(AMT_DRAWINGS_CURRENT = 0) / cast(count(), 'Float64') AS CC_INACTIVE_RATIO,

        /* === LIMIT MANAGEMENT === */
        avg(AMT_CREDIT_LIMIT_ACTUAL) AS CC_LIMIT_MEAN,
        max(AMT_CREDIT_LIMIT_ACTUAL) AS CC_LIMIT_MAX,

        /* Balance management */
        avg(AMT_BALANCE) AS CC_BALANCE_MEAN,
        max(AMT_BALANCE) AS CC_BALANCE_MAX,
        max(AMT_BALANCE) / nullIf(max(AMT_CREDIT_LIMIT_ACTUAL), 0) AS CC_MAX_UTIL_EVER

    FROM base
    GROUP BY SK_ID_CURR
)
SELECT *
FROM agg
