#!/bin/bash
# Clear Docker Hub cached images for credit-risk-scoring
# This forces fresh builds when serving-watcher pushes

DOCKER_USERNAME="ngnquanq"
IMAGE_NAME="credit-risk-scoring"

echo "🗑️  Clearing Docker Hub cache for $DOCKER_USERNAME/$IMAGE_NAME"
echo "============================================================"
echo ""
echo "⚠️  You need to do this manually via Docker Hub web UI:"
echo ""
echo "1. Go to: https://hub.docker.com/r/$DOCKER_USERNAME/$IMAGE_NAME/tags"
echo "2. Delete these tags (they contain old v2 Bentos):"
echo "   - v7, v8, v9, v10, v11, v12"
echo "   - latest (optional, but recommended)"
echo ""
echo "3. Then delete the InferenceServices:"
echo "   kubectl delete inferenceservice -n kserve --all"
echo ""
echo "4. The serving-watcher will rebuild with fresh Bentos from MinIO"
echo ""
echo "============================================================"
echo ""
echo "OR use Docker Hub API (requires token):"
echo ""
echo "# Get token"
echo "TOKEN=\$(curl -s -H \"Content-Type: application/json\" -X POST \\"
echo "  -d '{\"username\": \"$DOCKER_USERNAME\", \"password\": \"YOUR_PASSWORD\"}' \\"
echo "  https://hub.docker.com/v2/users/login/ | jq -r .token)"
echo ""
echo "# Delete tags"
echo "for tag in v7 v8 v9 v10 v11 v12 latest; do"
echo "  curl -X DELETE -H \"Authorization: JWT \$TOKEN\" \\"
echo "    https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/$IMAGE_NAME/tags/\$tag/"
echo "  echo \"Deleted \$tag\""
echo "done"
echo ""
