apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
  name: scoring-output-sink
  namespace: kserve
spec:
  bootstrapServers:
    - kafka-broker.data-services.svc.cluster.local:9092

  topic: hc.scoring

  contentMode: binary  # Publish clean JSON (not CloudEvents envelope)
