apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: api-gateway
type: Opaque
stringData:
  OPS_DB_PASSWORD: "ops_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
