fullnameOverride: minio

auth:
  rootUser: <set-via-MINIO_ACCESS_KEY> # Standardized across all MinIO instances
  rootPassword: "<set-via-MINIO_SECRET_KEY>" # Standardized across all MinIO instances
  usePasswordFiles: false
  useSecret: true
  forceNewKeys: true
defaultBuckets: "mlflow"

service:
  type: ClusterIP
  ports:
    api: 9000

console:
  enabled: true

networkPolicy:
  enabled: true
  allowExternal: true
  addExternalClientAccess: true

persistence:
  enabled: true
  size: 10Gi #just store the model weight, not that heavy
  storageClass: "standard" 
  mountPath: /bitnami/minio/data 

image:
  debug: true
  
defaultInitContainers:
  volumePermissions:
    enabled: false
