version: '3.8'

services:
  mlflow-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow-minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - mlflow_artifacts:/data
    ports:
      - "9002:9000"  # MLflow MinIO API
      - "9003:9001"  # MLflow MinIO Console
    networks:
      - hc-network

  mlflow-server:
    image: mlflow/mlflow:v3.1.1
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow_user:mlflow_password@mlflow-db:5432/mlflow_db
      MLFLOW_ARTIFACT_URI: s3://mlflow-artifacts/
      AWS_ACCESS_KEY_ID: minio_user
      AWS_SECRET_ACCESS_KEY: minio_password
      MLFLOW_S3_ENDPOINT_URL: http://mlflow-minio:9000
    ports:
      - "5000:5000"
    depends_on:
      - mlflow-db
      - mlflow-minio
    networks:
      - hc-network

volumes:
  mlflow_db_data:
  mlflow_artifacts:

networks:
  hc-network:
    external: true