apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast-registry
  namespace: feature-registry
  labels:
    component: feature-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi