apiVersion: v1
kind: PersistentVolume
metadata:
  name: feast-registry-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/feast-registry
    type: DirectoryOrCreate
