{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fs.fullname" . }}-redis
  labels:
    {{- include "fs.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fs.fullname" . }}-redis
  labels:
    {{- include "fs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
{{- end }}

