apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: model-serving
  annotations:
    serving.kserve.io/s3-endpoint: "yatai-minio.model-serving.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio_user
  AWS_SECRET_ACCESS_KEY: minio_password

