apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-watcher
  namespace: model-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlflow-watcher-job-creator
  namespace: kserve
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlflow-watcher-job-creator
  namespace: kserve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlflow-watcher-job-creator
subjects:
- kind: ServiceAccount
  name: mlflow-watcher
  namespace: model-registry
